FROM ubuntu:latest

WORKDIR /app

RUN apt-get update && apt-get install -y \
    wget \
    zip \
    libxt6 

RUN mkdir matlab_install matlab
RUN wget https://ssd.mathworks.com/supportfiles/downloads/R2020a/Release/3/deployment_files/installer/complete/glnxa64/MATLAB_Runtime_R2020a_Update_3_glnxa64.zip && \
    unzip MATLAB_Runtime_R2020a_Update_3_glnxa64.zip -d matlab_install
RUN /app/matlab_install/install -mode silent -agreeToLicense yes -destinationFolder /app/matlab
RUN rm -rf MATLAB_Runtime_R2020a_Update_3_glnxa64.zip && \
    rm -rf MATLAB_Runtime_R2020a_Update_3_glnxa64

RUN wget https://github.com/DCBIA-OrthoLab/TMJPI/releases/download/v1.0/DSCI_train
RUN wget https://github.com/DCBIA-OrthoLab/TMJPI/releases/download/v1.0/DSCI_predict
RUN chmod +x ./DSCI_train
RUN chmod +x ./DSCI_predict

RUN wget https://github.com/DCBIA-OrthoLab/TMJPI/releases/download/v1.0/train_af.xlsx
RUN wget https://github.com/DCBIA-OrthoLab/TMJPI/releases/download/v1.0/train_bl.csv
RUN wget https://github.com/DCBIA-OrthoLab/TMJPI/releases/download/v1.0/train_cl.csv
RUN wget https://github.com/DCBIA-OrthoLab/TMJPI/releases/download/v1.0/train_ct.csv

RUN wget https://github.com/DCBIA-OrthoLab/TMJPI/releases/download/v1.0/test_af.xlsx
RUN wget https://github.com/DCBIA-OrthoLab/TMJPI/releases/download/v1.0/test_bl.csv
RUN wget https://github.com/DCBIA-OrthoLab/TMJPI/releases/download/v1.0/test_cl.csv
RUN wget https://github.com/DCBIA-OrthoLab/TMJPI/releases/download/v1.0/test_ct.csv

RUN mkdir /app/.nvm
ENV NVM_DIR=/app/.nvm 
ENV NODE_VERSION=v14.16.0

RUN wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash \
	&& . $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && npm i clusterpost-execution -g

ENV PATH=$NVM_DIR/versions/node/$NODE_VERSION/bin:/app:$PATH
ENV LD_LIBRARY_PATH=/app/matlab/v98/runtime/glnxa64:/app/matlab/v98/bin/glnxa64:/app/matlab/v98/sys/os/glnxa64:/app/matlab/v98/sys/opengl/lib/glnxa64
